name: CI / CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yml
    with:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
